Adityaagr99 patch 1
aaiitkhyd/aaiitkhyd.github.io pull request #1
Opened 2018-01-24 09:28 UTC by adityaagr99

2018-01-24 09:35 UTC, kumardeepakr3 commented on index.html
> +                    <br><br><br><br><br><br><br><br><br><br><br><br><br>
This doesn't work when the browser height is less. Check this.

2018-01-24 09:36 UTC, kumardeepakr3 requested changes
Comments on PR

2018-01-24 09:38 UTC, adityaagr99 commented on index.html
> +                    <br><br><br><br><br><br><br><br><br><br><br><br><br>
okk I will do somthing else then

2018-01-25 03:16 UTC, kumardeepakr3 commented
Changes done in #4

2018-01-25 03:16 UTC, closed without merging